"""add phase six report workflow models

Revision ID: a2d9e7f41b53
Revises: f1c2d8e93a41
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "a2d9e7f41b53"
down_revision = "f1c2d8e93a41"
branch_labels = None
depends_on = None
jsonb = postgresql.JSONB(astext_type=sa.Text())


def _idx(prefix, table, columns):
    op.create_index(prefix, table, columns)


def upgrade() -> None:
    op.drop_constraint("ck_document_instances_status", "document_instances", type_="check")
    op.add_column("document_instances", sa.Column("template_version", sa.String(32), server_default="v1", nullable=False))
    op.create_check_constraint("ck_document_instances_status", "document_instances", "status IN ('draft', 'collecting_data', 'ready_for_generation', 'generating', 'in_review', 'revision_required', 'ready_for_export', 'completed', 'archived')")
    op.create_table("document_section_instances", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("document_instance_id", sa.Integer(), sa.ForeignKey("document_instances.id", ondelete="CASCADE"), nullable=False), sa.Column("template_section_id", sa.Integer(), sa.ForeignKey("template_sections.id", ondelete="RESTRICT"), nullable=False), sa.Column("parent_id", sa.Integer(), sa.ForeignKey("document_section_instances.id", ondelete="CASCADE")), sa.Column("section_code", sa.String(64), nullable=False), sa.Column("title", sa.String(255), nullable=False), sa.Column("level", sa.Integer(), nullable=False), sa.Column("sort_order", sa.Integer(), nullable=False), sa.Column("status", sa.String(32), server_default="empty", nullable=False), sa.Column("generation_enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False), sa.Column("current_draft_id", sa.Integer(), sa.ForeignKey("section_drafts.id", ondelete="SET NULL")), sa.Column("approved_version_id", sa.Integer(), sa.ForeignKey("section_draft_versions.id", ondelete="SET NULL")), sa.Column("blocked_reason", sa.Text()), sa.Column("source_fingerprint", sa.String(64)), sa.Column("stale_reason", sa.Text()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.UniqueConstraint("document_instance_id", "template_section_id", name="uq_document_section_instance"), sa.CheckConstraint("status IN ('empty', 'blocked', 'ready', 'queued', 'generating', 'generated', 'warning', 'reviewing', 'revision_required', 'approved', 'locked', 'stale', 'not_applicable')", name="ck_document_section_instances_status"))
    for name, cols in (("ix_document_section_instances_id", ["id"]), ("ix_document_section_instances_document_instance_id", ["document_instance_id"]), ("ix_document_section_instances_template_section_id", ["template_section_id"]), ("ix_document_section_instances_parent_id", ["parent_id"])): _idx(name, "document_section_instances", cols)
    op.create_table("section_dependencies", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("section_instance_id", sa.Integer(), sa.ForeignKey("document_section_instances.id", ondelete="CASCADE"), nullable=False), sa.Column("depends_on_section_instance_id", sa.Integer(), sa.ForeignKey("document_section_instances.id", ondelete="CASCADE"), nullable=False), sa.Column("dependency_type", sa.String(32), server_default="generation", nullable=False), sa.UniqueConstraint("section_instance_id", "depends_on_section_instance_id", "dependency_type", name="uq_section_dependency"), sa.CheckConstraint("dependency_type IN ('generation', 'review', 'approval')", name="ck_section_dependency_type"))
    _idx("ix_section_dependencies_id", "section_dependencies", ["id"]); _idx("ix_section_dependencies_section_instance_id", "section_dependencies", ["section_instance_id"]); _idx("ix_section_dependencies_depends_on_section_instance_id", "section_dependencies", ["depends_on_section_instance_id"])
    op.create_table("batch_generation_runs", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("document_instance_id", sa.Integer(), sa.ForeignKey("document_instances.id", ondelete="CASCADE"), nullable=False), sa.Column("status", sa.String(32), server_default="pending", nullable=False), sa.Column("total_sections", sa.Integer(), server_default="0", nullable=False), sa.Column("queued_sections", sa.Integer(), server_default="0", nullable=False), sa.Column("completed_sections", sa.Integer(), server_default="0", nullable=False), sa.Column("failed_sections", sa.Integer(), server_default="0", nullable=False), sa.Column("blocked_sections", sa.Integer(), server_default="0", nullable=False), sa.Column("partial_sections", sa.Integer(), server_default="0", nullable=False), sa.Column("started_by", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.Column("completed_at", sa.DateTime(timezone=True)), sa.CheckConstraint("status IN ('pending', 'running', 'completed', 'partial', 'failed')", name="ck_batch_generation_runs_status"))
    _idx("ix_batch_generation_runs_id", "batch_generation_runs", ["id"]); _idx("ix_batch_generation_runs_document_instance_id", "batch_generation_runs", ["document_instance_id"])
    op.create_table("batch_generation_items", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("batch_run_id", sa.Integer(), sa.ForeignKey("batch_generation_runs.id", ondelete="CASCADE"), nullable=False), sa.Column("section_instance_id", sa.Integer(), sa.ForeignKey("document_section_instances.id", ondelete="CASCADE"), nullable=False), sa.Column("generation_run_id", sa.Integer(), sa.ForeignKey("section_generation_runs.id", ondelete="SET NULL")), sa.Column("status", sa.String(32), server_default="queued", nullable=False), sa.Column("error_message", sa.String(500)), sa.CheckConstraint("status IN ('queued', 'running', 'completed', 'partial', 'failed', 'blocked', 'skipped')", name="ck_batch_generation_items_status"))
    _idx("ix_batch_generation_items_id", "batch_generation_items", ["id"]); _idx("ix_batch_generation_items_batch_run_id", "batch_generation_items", ["batch_run_id"]); _idx("ix_batch_generation_items_section_instance_id", "batch_generation_items", ["section_instance_id"])
    op.create_table("section_reviews", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("section_instance_id", sa.Integer(), sa.ForeignKey("document_section_instances.id", ondelete="CASCADE"), nullable=False), sa.Column("draft_version_id", sa.Integer(), sa.ForeignKey("section_draft_versions.id", ondelete="SET NULL")), sa.Column("reviewer_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("status", sa.String(32), nullable=False), sa.Column("comment", sa.Text()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.CheckConstraint("status IN ('approved', 'revision_required', 'rejected')", name="ck_section_reviews_status"))
    _idx("ix_section_reviews_id", "section_reviews", ["id"]); _idx("ix_section_reviews_section_instance_id", "section_reviews", ["section_instance_id"])
    op.create_table("document_validation_runs", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("document_instance_id", sa.Integer(), sa.ForeignKey("document_instances.id", ondelete="CASCADE"), nullable=False), sa.Column("status", sa.String(32), server_default="running", nullable=False), sa.Column("issues_count", sa.Integer(), server_default="0", nullable=False), sa.Column("critical_count", sa.Integer(), server_default="0", nullable=False), sa.Column("warning_count", sa.Integer(), server_default="0", nullable=False), sa.Column("created_by", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.Column("completed_at", sa.DateTime(timezone=True)), sa.CheckConstraint("status IN ('running', 'completed', 'failed')", name="ck_document_validation_runs_status"))
    _idx("ix_document_validation_runs_id", "document_validation_runs", ["id"]); _idx("ix_document_validation_runs_document_instance_id", "document_validation_runs", ["document_instance_id"])
    op.create_table("document_validation_issues", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("validation_run_id", sa.Integer(), sa.ForeignKey("document_validation_runs.id", ondelete="CASCADE"), nullable=False), sa.Column("issue_type", sa.String(64), nullable=False), sa.Column("severity", sa.String(32), nullable=False), sa.Column("section_a_id", sa.Integer(), sa.ForeignKey("document_section_instances.id", ondelete="SET NULL")), sa.Column("section_b_id", sa.Integer(), sa.ForeignKey("document_section_instances.id", ondelete="SET NULL")), sa.Column("entity_type", sa.String(64)), sa.Column("field_name", sa.String(64)), sa.Column("expected_value", sa.Text()), sa.Column("actual_value", sa.Text()), sa.Column("message", sa.Text(), nullable=False), sa.Column("status", sa.String(32), server_default="open", nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.Column("resolved_at", sa.DateTime(timezone=True)), sa.CheckConstraint("severity IN ('critical', 'warning', 'info')", name="ck_document_validation_issues_severity"), sa.CheckConstraint("status IN ('open', 'resolved', 'ignored')", name="ck_document_validation_issues_status"))
    _idx("ix_document_validation_issues_id", "document_validation_issues", ["id"]); _idx("ix_document_validation_issues_validation_run_id", "document_validation_issues", ["validation_run_id"])
    op.create_table("audit_events", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id", ondelete="CASCADE")), sa.Column("document_instance_id", sa.Integer(), sa.ForeignKey("document_instances.id", ondelete="CASCADE")), sa.Column("section_instance_id", sa.Integer(), sa.ForeignKey("document_section_instances.id", ondelete="CASCADE")), sa.Column("action", sa.String(64), nullable=False), sa.Column("metadata", jsonb), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False))
    _idx("ix_audit_events_id", "audit_events", ["id"]); _idx("ix_audit_events_user_id", "audit_events", ["user_id"]); _idx("ix_audit_events_project_id", "audit_events", ["project_id"]); _idx("ix_audit_events_document_instance_id", "audit_events", ["document_instance_id"]); _idx("ix_audit_events_section_instance_id", "audit_events", ["section_instance_id"])


def downgrade() -> None:
    for table in ("audit_events", "document_validation_issues", "document_validation_runs", "section_reviews", "batch_generation_items", "batch_generation_runs", "section_dependencies", "document_section_instances"):
        op.drop_table(table)
    op.drop_constraint("ck_document_instances_status", "document_instances", type_="check")
    op.drop_column("document_instances", "template_version")
    op.create_check_constraint("ck_document_instances_status", "document_instances", "status IN ('draft', 'generating', 'reviewing', 'completed')")
