"""add phase seven professional review and quality control

Revision ID: b3e1f8d52a64
Revises: a2d9e7f41b53
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "b3e1f8d52a64"
down_revision = "a2d9e7f41b53"
branch_labels = None
depends_on = None
jsonb = postgresql.JSONB(astext_type=sa.Text())


def upgrade() -> None:
    op.create_table("review_rule_sets", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("name", sa.String(255), nullable=False), sa.Column("code", sa.String(128), unique=True, nullable=False), sa.Column("description", sa.Text()), sa.Column("version", sa.String(32), server_default="v1", nullable=False), sa.Column("status", sa.String(32), server_default="active", nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False))
    op.create_index("ix_review_rule_sets_id", "review_rule_sets", ["id"])
    op.create_table("professional_rules", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("rule_set_id", sa.Integer(), sa.ForeignKey("review_rule_sets.id", ondelete="CASCADE"), nullable=False), sa.Column("code", sa.String(128), nullable=False), sa.Column("name", sa.String(255), nullable=False), sa.Column("category", sa.String(64), server_default="general", nullable=False), sa.Column("description", sa.Text()), sa.Column("severity", sa.String(32), server_default="major", nullable=False), sa.Column("rule_type", sa.String(32), nullable=False), sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False), sa.Column("config", jsonb), sa.Column("version", sa.String(32), server_default="v1", nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.UniqueConstraint("rule_set_id", "code", name="uq_professional_rule_code"))
    op.create_index("ix_professional_rules_id", "professional_rules", ["id"]); op.create_index("ix_professional_rules_rule_set_id", "professional_rules", ["rule_set_id"])
    op.create_table("review_checklists", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("rule_set_id", sa.Integer(), sa.ForeignKey("review_rule_sets.id", ondelete="CASCADE"), nullable=False), sa.Column("code", sa.String(128), nullable=False), sa.Column("name", sa.String(255), nullable=False), sa.Column("scope_type", sa.String(32), server_default="document", nullable=False), sa.Column("section_code", sa.String(64)), sa.Column("description", sa.Text()), sa.Column("required", sa.Boolean(), server_default=sa.text("false"), nullable=False), sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False), sa.UniqueConstraint("rule_set_id", "code", name="uq_review_checklist_code"))
    op.create_index("ix_review_checklists_id", "review_checklists", ["id"]); op.create_index("ix_review_checklists_rule_set_id", "review_checklists", ["rule_set_id"])
    op.add_column("document_templates", sa.Column("review_rule_set_id", sa.Integer(), sa.ForeignKey("review_rule_sets.id", ondelete="SET NULL"), nullable=True))
    op.create_table("professional_review_runs", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("document_instance_id", sa.Integer(), sa.ForeignKey("document_instances.id", ondelete="CASCADE"), nullable=False), sa.Column("status", sa.String(32), server_default="pending", nullable=False), sa.Column("review_mode", sa.String(32), server_default="full", nullable=False), sa.Column("rule_set_id", sa.Integer(), sa.ForeignKey("review_rule_sets.id", ondelete="SET NULL")), sa.Column("rule_set_version", sa.String(32)), sa.Column("ai_provider", sa.String(64)), sa.Column("ai_model", sa.String(128)), sa.Column("issues_count", sa.Integer(), server_default="0", nullable=False), sa.Column("critical_count", sa.Integer(), server_default="0", nullable=False), sa.Column("major_count", sa.Integer(), server_default="0", nullable=False), sa.Column("minor_count", sa.Integer(), server_default="0", nullable=False), sa.Column("input_tokens", sa.Integer()), sa.Column("output_tokens", sa.Integer()), sa.Column("ai_calls", sa.Integer(), server_default="0", nullable=False), sa.Column("error_message", sa.String(500)), sa.Column("started_by", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.Column("completed_at", sa.DateTime(timezone=True)), sa.CheckConstraint("status IN ('pending', 'running', 'completed', 'partial', 'failed')", name="ck_professional_review_runs_status"))
    op.create_index("ix_professional_review_runs_id", "professional_review_runs", ["id"]); op.create_index("ix_professional_review_runs_document_instance_id", "professional_review_runs", ["document_instance_id"])
    op.create_table("review_tasks", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("review_run_id", sa.Integer(), sa.ForeignKey("professional_review_runs.id", ondelete="CASCADE"), nullable=False), sa.Column("scope_type", sa.String(32), nullable=False), sa.Column("section_instance_id", sa.Integer(), sa.ForeignKey("document_section_instances.id", ondelete="SET NULL")), sa.Column("section_group", sa.String(128)), sa.Column("review_type", sa.String(64), nullable=False), sa.Column("status", sa.String(32), server_default="pending", nullable=False), sa.Column("prompt_version", sa.String(64)), sa.Column("rule_set_version", sa.String(32)), sa.Column("error_message", sa.String(500)), sa.Column("started_at", sa.DateTime(timezone=True)), sa.Column("completed_at", sa.DateTime(timezone=True)), sa.CheckConstraint("status IN ('pending', 'running', 'completed', 'failed', 'skipped')", name="ck_review_tasks_status"))
    op.create_index("ix_review_tasks_id", "review_tasks", ["id"]); op.create_index("ix_review_tasks_review_run_id", "review_tasks", ["review_run_id"])
    op.create_table("review_issues", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("document_instance_id", sa.Integer(), sa.ForeignKey("document_instances.id", ondelete="CASCADE"), nullable=False), sa.Column("review_run_id", sa.Integer(), sa.ForeignKey("professional_review_runs.id", ondelete="CASCADE"), nullable=False), sa.Column("section_instance_id", sa.Integer(), sa.ForeignKey("document_section_instances.id", ondelete="SET NULL")), sa.Column("draft_version_id", sa.Integer(), sa.ForeignKey("section_draft_versions.id", ondelete="SET NULL")), sa.Column("issue_source", sa.String(32), nullable=False), sa.Column("issue_type", sa.String(64), nullable=False), sa.Column("severity", sa.String(32), nullable=False), sa.Column("title", sa.String(255), nullable=False), sa.Column("description", sa.Text(), nullable=False), sa.Column("evidence", jsonb), sa.Column("suggestion", sa.Text()), sa.Column("related_fact_ids", jsonb), sa.Column("related_citation_ids", jsonb), sa.Column("related_knowledge_chunk_ids", jsonb), sa.Column("confidence", sa.Numeric(4, 3)), sa.Column("fingerprint", sa.String(64), nullable=False), sa.Column("status", sa.String(32), server_default="open", nullable=False), sa.Column("dismissal_reason", sa.Text()), sa.Column("resolved_at", sa.DateTime(timezone=True)), sa.Column("resolved_by", sa.Integer(), sa.ForeignKey("users.id", ondelete="SET NULL")), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.UniqueConstraint("review_run_id", "fingerprint", name="uq_review_issue_fingerprint"), sa.CheckConstraint("severity IN ('critical', 'major', 'minor', 'info')", name="ck_review_issues_severity"), sa.CheckConstraint("status IN ('open', 'accepted', 'fixed', 'dismissed', 'needs_review', 'stale')", name="ck_review_issues_status"))
    op.create_index("ix_review_issues_id", "review_issues", ["id"]); op.create_index("ix_review_issues_document_instance_id", "review_issues", ["document_instance_id"]); op.create_index("ix_review_issues_review_run_id", "review_issues", ["review_run_id"])
    op.create_table("review_checklist_results", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("review_task_id", sa.Integer(), sa.ForeignKey("review_tasks.id", ondelete="CASCADE"), nullable=False), sa.Column("checklist_id", sa.Integer(), sa.ForeignKey("review_checklists.id", ondelete="SET NULL")), sa.Column("check_code", sa.String(128), nullable=False), sa.Column("status", sa.String(32), nullable=False), sa.Column("evidence", jsonb), sa.Column("message", sa.Text()), sa.Column("reviewed_by", sa.Integer(), sa.ForeignKey("users.id", ondelete="SET NULL")), sa.Column("reviewed_at", sa.DateTime(timezone=True)), sa.UniqueConstraint("review_task_id", "check_code", name="uq_review_checklist_result"))
    op.create_index("ix_review_checklist_results_id", "review_checklist_results", ["id"]); op.create_index("ix_review_checklist_results_review_task_id", "review_checklist_results", ["review_task_id"])
    op.create_table("quality_score_results", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("document_instance_id", sa.Integer(), sa.ForeignKey("document_instances.id", ondelete="CASCADE"), nullable=False), sa.Column("review_run_id", sa.Integer(), sa.ForeignKey("professional_review_runs.id", ondelete="SET NULL")), sa.Column("overall_score", sa.Numeric(5, 2), nullable=False), sa.Column("data_integrity_score", sa.Numeric(5, 2), nullable=False), sa.Column("citation_score", sa.Numeric(5, 2), nullable=False), sa.Column("coverage_score", sa.Numeric(5, 2), nullable=False), sa.Column("completeness_score", sa.Numeric(5, 2), nullable=False), sa.Column("consistency_score", sa.Numeric(5, 2), nullable=False), sa.Column("critical_issue_count", sa.Integer(), server_default="0", nullable=False), sa.Column("major_issue_count", sa.Integer(), server_default="0", nullable=False), sa.Column("quality_passed", sa.Boolean(), server_default=sa.text("false"), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False))
    op.create_index("ix_quality_score_results_id", "quality_score_results", ["id"]); op.create_index("ix_quality_score_results_document_instance_id", "quality_score_results", ["document_instance_id"])


def downgrade() -> None:
    for table in ("quality_score_results", "review_checklist_results", "review_issues", "review_tasks", "professional_review_runs"):
        op.drop_table(table)
    op.drop_column("document_templates", "review_rule_set_id")
    op.drop_table("review_checklists"); op.drop_table("professional_rules"); op.drop_table("review_rule_sets")
