"""add phase four knowledge base infrastructure

Revision ID: c4f1a9e72d10
Revises: b7e4c2d91a30
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "c4f1a9e72d10"
down_revision = "b7e4c2d91a30"
branch_labels = None
depends_on = None
jsonb = postgresql.JSONB(astext_type=sa.Text())


def upgrade() -> None:
    # 在本地可用时启用 pgvector；没有扩展时保持 JSON 向量后端，不伪造启用成功。
    op.execute("""DO $$ BEGIN IF EXISTS (SELECT 1 FROM pg_available_extensions WHERE name = 'vector') THEN CREATE EXTENSION IF NOT EXISTS vector; END IF; END $$;""")
    ts = [sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False)]
    op.create_table("knowledge_bases", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("name", sa.String(255), nullable=False), sa.Column("description", sa.Text()), sa.Column("scope", sa.String(32), server_default="private", nullable=False), sa.Column("status", sa.String(32), server_default="active", nullable=False), sa.Column("created_by", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), *ts, sa.CheckConstraint("scope IN ('system', 'private')", name="ck_knowledge_bases_scope"))
    op.create_index("ix_knowledge_bases_id", "knowledge_bases", ["id"])
    op.create_index("ix_knowledge_bases_created_by", "knowledge_bases", ["created_by"])
    op.create_table("knowledge_categories", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("code", sa.String(64), unique=True, nullable=False), sa.Column("name", sa.String(128), nullable=False))
    op.create_index("ix_knowledge_categories_id", "knowledge_categories", ["id"])
    op.create_table("knowledge_documents", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("knowledge_base_id", sa.Integer(), sa.ForeignKey("knowledge_bases.id", ondelete="CASCADE"), nullable=False), sa.Column("title", sa.String(500), nullable=False), sa.Column("document_type", sa.String(64), server_default="other", nullable=False), sa.Column("document_number", sa.String(128)), sa.Column("issuing_authority", sa.String(255)), sa.Column("publish_date", sa.Date()), sa.Column("effective_date", sa.Date()), sa.Column("expiry_date", sa.Date()), sa.Column("version", sa.String(64)), sa.Column("revision", sa.String(64)), sa.Column("status", sa.String(32), server_default="unknown", nullable=False), sa.Column("source_url", sa.String(1000)), sa.Column("original_file_name", sa.String(255), nullable=False), sa.Column("storage_path", sa.String(512), nullable=False), sa.Column("mime_type", sa.String(128)), sa.Column("file_size", sa.Integer(), server_default="0", nullable=False), sa.Column("sha256", sa.String(64), nullable=False), sa.Column("language", sa.String(16), server_default="zh", nullable=False), sa.Column("country", sa.String(64)), sa.Column("province", sa.String(64)), sa.Column("city", sa.String(64)), sa.Column("district", sa.String(64)), sa.Column("source_authority", sa.String(32), server_default="unknown", nullable=False), sa.Column("parser_status", sa.String(32), server_default="pending", nullable=False), sa.Column("index_status", sa.String(32), server_default="pending", nullable=False), sa.Column("parser_name", sa.String(64)), sa.Column("parser_version", sa.String(32)), sa.Column("parsed_text", sa.Text()), sa.Column("parsed_content", jsonb), sa.Column("error_message", sa.String(500)), sa.Column("deleted_at", sa.DateTime(timezone=True)), sa.Column("created_by", sa.Integer(), sa.ForeignKey("users.id", ondelete="SET NULL")), *ts, sa.CheckConstraint("status IN ('draft', 'active', 'repealed', 'expired', 'superseded', 'unknown')", name="ck_knowledge_documents_status"), sa.CheckConstraint("parser_status IN ('pending', 'parsing', 'parsed', 'failed')", name="ck_knowledge_documents_parser_status"), sa.CheckConstraint("index_status IN ('pending', 'chunking', 'chunked', 'embedding', 'indexed', 'failed', 'partial')", name="ck_knowledge_documents_index_status"))
    for name, table, columns in [("ix_knowledge_documents_id", "knowledge_documents", ["id"]), ("ix_knowledge_documents_knowledge_base_id", "knowledge_documents", ["knowledge_base_id"]), ("ix_knowledge_documents_document_number", "knowledge_documents", ["document_number"]), ("ix_knowledge_documents_sha256", "knowledge_documents", ["sha256"])]: op.create_index(name, table, columns)
    op.create_table("knowledge_document_categories", sa.Column("knowledge_document_id", sa.Integer(), sa.ForeignKey("knowledge_documents.id", ondelete="CASCADE"), primary_key=True), sa.Column("category_id", sa.Integer(), sa.ForeignKey("knowledge_categories.id", ondelete="CASCADE"), primary_key=True), sa.UniqueConstraint("knowledge_document_id", "category_id", name="uq_knowledge_document_category"))
    op.create_table("knowledge_document_relations", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("document_id", sa.Integer(), sa.ForeignKey("knowledge_documents.id", ondelete="CASCADE"), nullable=False), sa.Column("related_document_id", sa.Integer(), sa.ForeignKey("knowledge_documents.id", ondelete="CASCADE"), nullable=False), sa.Column("relation_type", sa.String(32), server_default="related", nullable=False), sa.UniqueConstraint("document_id", "related_document_id", "relation_type", name="uq_knowledge_document_relation"))
    op.create_index("ix_knowledge_document_relations_id", "knowledge_document_relations", ["id"])
    op.create_index("ix_knowledge_document_relations_document_id", "knowledge_document_relations", ["document_id"])
    op.create_index("ix_knowledge_document_relations_related_document_id", "knowledge_document_relations", ["related_document_id"])
    op.create_table("knowledge_chunks", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("knowledge_document_id", sa.Integer(), sa.ForeignKey("knowledge_documents.id", ondelete="CASCADE"), nullable=False), sa.Column("chunk_index", sa.Integer(), nullable=False), sa.Column("content", sa.Text(), nullable=False), sa.Column("content_type", sa.String(32), server_default="paragraph", nullable=False), sa.Column("section_title", sa.String(500)), sa.Column("section_level", sa.Integer()), sa.Column("section_path", jsonb), sa.Column("article_number", sa.String(64)), sa.Column("page_start", sa.Integer()), sa.Column("page_end", sa.Integer()), sa.Column("table_index", sa.Integer()), sa.Column("structured_table", jsonb), sa.Column("token_count", sa.Integer(), server_default="0", nullable=False), sa.Column("character_count", sa.Integer(), server_default="0", nullable=False), sa.Column("metadata", jsonb), sa.Column("content_hash", sa.String(64), nullable=False), sa.Column("chunk_fingerprint", sa.String(64), nullable=False), sa.Column("embedding_status", sa.String(32), server_default="pending", nullable=False), *ts, sa.UniqueConstraint("knowledge_document_id", "chunk_fingerprint", name="uq_knowledge_chunk_fingerprint"))
    op.create_index("ix_knowledge_chunks_id", "knowledge_chunks", ["id"])
    op.create_index("ix_knowledge_chunks_knowledge_document_id", "knowledge_chunks", ["knowledge_document_id"])
    op.create_index("ix_knowledge_chunks_document_index", "knowledge_chunks", ["knowledge_document_id", "chunk_index"])
    op.create_table("knowledge_chunk_embeddings", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("chunk_id", sa.Integer(), sa.ForeignKey("knowledge_chunks.id", ondelete="CASCADE"), nullable=False), sa.Column("provider", sa.String(64), nullable=False), sa.Column("model", sa.String(128), nullable=False), sa.Column("dimension", sa.Integer(), nullable=False), sa.Column("version", sa.String(64), server_default="v1", nullable=False), sa.Column("distance_metric", sa.String(32), server_default="cosine", nullable=False), sa.Column("embedding", jsonb, nullable=False), sa.Column("token_count", sa.Integer()), sa.Column("api_calls", sa.Integer(), server_default="1", nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.UniqueConstraint("chunk_id", "provider", "model", "version", name="uq_knowledge_chunk_embedding_version"))
    op.create_index("ix_knowledge_chunk_embeddings_id", "knowledge_chunk_embeddings", ["id"])
    op.create_index("ix_knowledge_chunk_embeddings_chunk_id", "knowledge_chunk_embeddings", ["chunk_id"])
    op.create_table("knowledge_index_runs", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("knowledge_document_id", sa.Integer(), sa.ForeignKey("knowledge_documents.id", ondelete="CASCADE"), nullable=False), sa.Column("status", sa.String(32), server_default="running", nullable=False), sa.Column("stage", sa.String(32), server_default="parse", nullable=False), sa.Column("parser_version", sa.String(32)), sa.Column("chunker_version", sa.String(32), server_default="structure-v1", nullable=False), sa.Column("embedding_provider", sa.String(64)), sa.Column("embedding_model", sa.String(128)), sa.Column("chunks_created", sa.Integer(), server_default="0", nullable=False), sa.Column("chunks_embedded", sa.Integer(), server_default="0", nullable=False), sa.Column("embedding_calls", sa.Integer(), server_default="0", nullable=False), sa.Column("token_count", sa.Integer(), server_default="0", nullable=False), sa.Column("error_message", sa.String(500)), sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.Column("completed_at", sa.DateTime(timezone=True)), sa.CheckConstraint("status IN ('running', 'completed', 'failed', 'partial')", name="ck_knowledge_index_runs_status"))
    op.create_index("ix_knowledge_index_runs_id", "knowledge_index_runs", ["id"])
    op.create_index("ix_knowledge_index_runs_knowledge_document_id", "knowledge_index_runs", ["knowledge_document_id"])


def downgrade() -> None:
    for table in ("knowledge_index_runs", "knowledge_chunk_embeddings", "knowledge_chunks", "knowledge_document_relations", "knowledge_document_categories", "knowledge_documents", "knowledge_categories", "knowledge_bases"):
        op.drop_table(table)
