"""add phase five controlled section generation models

Revision ID: e8b1c7d92f30
Revises: d7a6b8f31c42
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "e8b1c7d92f30"
down_revision = "d7a6b8f31c42"
branch_labels = None
depends_on = None
jsonb = postgresql.JSONB(astext_type=sa.Text())


def _ts():
    return [sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False)]


def upgrade() -> None:
    op.create_table("document_templates", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("name", sa.String(255), nullable=False), sa.Column("code", sa.String(128), unique=True, nullable=False), sa.Column("document_type", sa.String(64), nullable=False), sa.Column("description", sa.Text()), sa.Column("version", sa.String(32), server_default="v1", nullable=False), sa.Column("status", sa.String(32), server_default="active", nullable=False), sa.Column("created_by", sa.Integer(), sa.ForeignKey("users.id", ondelete="SET NULL")), *_ts(), sa.CheckConstraint("status IN ('draft', 'active', 'disabled')", name="ck_document_templates_status"))
    op.create_index("ix_document_templates_id", "document_templates", ["id"])
    op.create_table("template_sections", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("template_id", sa.Integer(), sa.ForeignKey("document_templates.id", ondelete="CASCADE"), nullable=False), sa.Column("parent_id", sa.Integer(), sa.ForeignKey("template_sections.id", ondelete="CASCADE")), sa.Column("section_code", sa.String(64), nullable=False), sa.Column("title", sa.String(255), nullable=False), sa.Column("level", sa.Integer(), server_default="1", nullable=False), sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False), sa.Column("description", sa.Text()), sa.Column("generation_mode", sa.String(32), server_default="manual", nullable=False), sa.Column("required", sa.Boolean(), server_default=sa.text("false"), nullable=False), sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False), *_ts(), sa.UniqueConstraint("template_id", "section_code", name="uq_template_section_code"))
    for name, cols in (("ix_template_sections_id", ["id"]), ("ix_template_sections_template_id", ["template_id"]), ("ix_template_sections_parent_id", ["parent_id"])): op.create_index(name, "template_sections", cols)
    op.create_table("section_generation_configs", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("section_id", sa.Integer(), sa.ForeignKey("template_sections.id", ondelete="CASCADE"), unique=True, nullable=False), sa.Column("prompt_template", sa.Text(), nullable=False), sa.Column("required_entity_types", jsonb), sa.Column("required_fields", jsonb), sa.Column("knowledge_categories", jsonb), sa.Column("knowledge_document_types", jsonb), sa.Column("jurisdiction_policy", sa.String(32), server_default="project", nullable=False), sa.Column("retrieval_query_template", sa.String(500)), sa.Column("max_project_context", sa.Integer(), server_default="10", nullable=False), sa.Column("max_knowledge_context", sa.Integer(), server_default="8", nullable=False), sa.Column("temperature", sa.Float(), server_default="0.2", nullable=False), sa.Column("generation_schema", jsonb), sa.Column("prompt_version", sa.String(64), server_default="section-v1", nullable=False), *_ts())
    op.create_index("ix_section_generation_configs_id", "section_generation_configs", ["id"])
    op.create_table("document_instances", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False), sa.Column("template_id", sa.Integer(), sa.ForeignKey("document_templates.id", ondelete="RESTRICT"), nullable=False), sa.Column("title", sa.String(255), nullable=False), sa.Column("status", sa.String(32), server_default="draft", nullable=False), sa.Column("reference_date", sa.Date()), sa.Column("created_by", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), *_ts(), sa.CheckConstraint("status IN ('draft', 'generating', 'reviewing', 'completed')", name="ck_document_instances_status"))
    for name, cols in (("ix_document_instances_id", ["id"]), ("ix_document_instances_project_id", ["project_id"]), ("ix_document_instances_template_id", ["template_id"])): op.create_index(name, "document_instances", cols)
    op.create_table("section_generation_runs", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False), sa.Column("document_instance_id", sa.Integer(), sa.ForeignKey("document_instances.id", ondelete="CASCADE"), nullable=False), sa.Column("section_id", sa.Integer(), sa.ForeignKey("template_sections.id", ondelete="CASCADE"), nullable=False), sa.Column("status", sa.String(32), server_default="pending", nullable=False), sa.Column("ai_provider", sa.String(64)), sa.Column("model", sa.String(128)), sa.Column("prompt_version", sa.String(64)), sa.Column("input_tokens", sa.Integer()), sa.Column("output_tokens", sa.Integer()), sa.Column("project_fact_count", sa.Integer(), server_default="0", nullable=False), sa.Column("project_source_count", sa.Integer(), server_default="0", nullable=False), sa.Column("knowledge_source_count", sa.Integer(), server_default="0", nullable=False), sa.Column("retrieval_ms", sa.Integer()), sa.Column("generation_ms", sa.Integer()), sa.Column("total_duration_ms", sa.Integer()), sa.Column("error_message", sa.String(500)), sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.Column("completed_at", sa.DateTime(timezone=True)), sa.CheckConstraint("status IN ('pending', 'retrieving', 'generating', 'validating', 'completed', 'partial', 'failed', 'blocked')", name="ck_section_generation_runs_status"))
    for name, cols in (("ix_section_generation_runs_id", ["id"]), ("ix_section_generation_runs_project_id", ["project_id"]), ("ix_section_generation_runs_document_instance_id", ["document_instance_id"]), ("ix_section_generation_runs_section_id", ["section_id"])): op.create_index(name, "section_generation_runs", cols)
    op.create_table("section_drafts", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("project_id", sa.Integer(), sa.ForeignKey("projects.id", ondelete="CASCADE"), nullable=False), sa.Column("document_instance_id", sa.Integer(), sa.ForeignKey("document_instances.id", ondelete="CASCADE"), nullable=False), sa.Column("template_id", sa.Integer(), sa.ForeignKey("document_templates.id", ondelete="CASCADE"), nullable=False), sa.Column("section_id", sa.Integer(), sa.ForeignKey("template_sections.id", ondelete="CASCADE"), nullable=False), sa.Column("generation_run_id", sa.Integer(), sa.ForeignKey("section_generation_runs.id", ondelete="SET NULL")), sa.Column("content", sa.Text(), server_default="", nullable=False), sa.Column("ai_original_content", sa.Text()), sa.Column("status", sa.String(32), server_default="draft", nullable=False), sa.Column("version", sa.Integer(), server_default="1", nullable=False), sa.Column("citations", jsonb), sa.Column("missing_information", jsonb), sa.Column("warnings", jsonb), sa.Column("generation_metadata", jsonb), sa.Column("created_by", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), *_ts(), sa.UniqueConstraint("document_instance_id", "section_id", name="uq_section_draft_instance_section"), sa.CheckConstraint("status IN ('draft', 'generated', 'reviewed', 'approved', 'rejected', 'partial', 'blocked')", name="ck_section_drafts_status"))
    for name, cols in (("ix_section_drafts_id", ["id"]), ("ix_section_drafts_project_id", ["project_id"]), ("ix_section_drafts_document_instance_id", ["document_instance_id"]), ("ix_section_drafts_section_id", ["section_id"])): op.create_index(name, "section_drafts", cols)
    op.create_table("section_draft_versions", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("draft_id", sa.Integer(), sa.ForeignKey("section_drafts.id", ondelete="CASCADE"), nullable=False), sa.Column("version", sa.Integer(), nullable=False), sa.Column("content", sa.Text(), nullable=False), sa.Column("status", sa.String(32), nullable=False), sa.Column("saved_by", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False), sa.UniqueConstraint("draft_id", "version", name="uq_section_draft_version"))
    op.create_index("ix_section_draft_versions_id", "section_draft_versions", ["id"])
    op.create_index("ix_section_draft_versions_draft_id", "section_draft_versions", ["draft_id"])
    op.create_table("generation_sources", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("generation_run_id", sa.Integer(), sa.ForeignKey("section_generation_runs.id", ondelete="CASCADE"), nullable=False), sa.Column("source_type", sa.String(32), nullable=False), sa.Column("source_id", sa.Integer(), nullable=False), sa.Column("context_source_id", sa.String(32), nullable=False), sa.Column("rank", sa.Integer()), sa.Column("score", sa.Float()), sa.Column("metadata", jsonb), sa.UniqueConstraint("generation_run_id", "source_type", "source_id", name="uq_generation_source"))
    op.create_index("ix_generation_sources_id", "generation_sources", ["id"])
    op.create_index("ix_generation_sources_generation_run_id", "generation_sources", ["generation_run_id"])
    op.create_table("section_citations", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("section_draft_id", sa.Integer(), sa.ForeignKey("section_drafts.id", ondelete="CASCADE"), nullable=False), sa.Column("generation_run_id", sa.Integer(), sa.ForeignKey("section_generation_runs.id", ondelete="CASCADE"), nullable=False), sa.Column("source_type", sa.String(32), nullable=False), sa.Column("source_id", sa.Integer(), nullable=False), sa.Column("context_source_id", sa.String(32), nullable=False), sa.Column("claim_text", sa.Text(), nullable=False), sa.Column("citation_order", sa.Integer(), server_default="0", nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False))
    op.create_index("ix_section_citations_id", "section_citations", ["id"])
    op.create_index("ix_section_citations_section_draft_id", "section_citations", ["section_draft_id"])
    op.create_index("ix_section_citations_generation_run_id", "section_citations", ["generation_run_id"])


def downgrade() -> None:
    for table in ("section_citations", "generation_sources", "section_draft_versions", "section_drafts", "section_generation_runs", "document_instances", "section_generation_configs", "template_sections", "document_templates"):
        op.drop_table(table)
