<template>
  <div class="admin-shell">
    <aside><div class="admin-brand"><span>E</span><div><strong>EnvAI</strong><small>平台运营</small></div></div><nav><p>运营中心</p><router-link to="/admin" exact-active-class="active"><el-icon><Odometer /></el-icon>平台概览</router-link><router-link to="/admin/organizations" active-class="active"><el-icon><OfficeBuilding /></el-icon>企业工作区</router-link></nav><button class="return" @click="$router.push('/projects')"><el-icon><Back /></el-icon>返回企业端</button></aside>
    <section><header><div><span class="status-dot"></span>平台运行正常</div><button @click="$router.push('/projects')">企业工作台</button></header><main><router-view /></main></section>
  </div>
</template>
<script setup lang="ts">import { Back, Odometer, OfficeBuilding } from '@element-plus/icons-vue';</script>
<style scoped>
.admin-shell{min-height:100vh;display:grid;grid-template-columns:235px 1fr;background:#f5f5f7}.admin-shell>aside{position:fixed;inset:0 auto 0 0;width:235px;padding:21px 15px;display:flex;flex-direction:column;border-right:1px solid rgba(0,0,0,.07);background:#fff}.admin-brand{height:48px;padding:0 8px;display:flex;align-items:center;gap:10px}.admin-brand>span{width:33px;height:33px;display:grid;place-items:center;border-radius:11px;color:#fff;background:#1d1d1f;font-size:14px;font-weight:700}.admin-brand strong,.admin-brand small{display:block}.admin-brand strong{font-size:15px}.admin-brand small{margin-top:2px;color:#86868b;font-size:9px}.admin-shell nav{margin-top:25px}.admin-shell nav p{margin:0 10px 8px;color:#a1a1a6;font-size:9px;font-weight:700;letter-spacing:.08em}.admin-shell nav a{height:43px;padding:0 12px;display:flex;align-items:center;gap:10px;border-radius:12px;color:#515154;font-size:12px;font-weight:600}.admin-shell nav a:hover{background:#f5f5f7}.admin-shell nav a.active{color:#1d1d1f;background:#ededf0}.return{height:41px;margin-top:auto;display:flex;align-items:center;justify-content:center;gap:7px;border:0;border-radius:12px;background:#f2f2f4;color:#515154;cursor:pointer}.admin-shell>section{grid-column:2}.admin-shell>section>header{position:sticky;top:0;z-index:10;height:64px;padding:0 30px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid rgba(0,0,0,.06);background:rgba(245,245,247,.84);backdrop-filter:blur(20px);color:#6e6e73;font-size:10px}.admin-shell>section>header>div{display:flex;align-items:center;gap:7px}.status-dot{width:7px;height:7px;border-radius:50%;background:#34c759}.admin-shell>section>header button{border:0;background:transparent;color:#0071e3;cursor:pointer;font-size:11px}.admin-shell main{padding:30px 34px 60px}@media(max-width:750px){.admin-shell{grid-template-columns:72px 1fr}.admin-shell>aside{width:72px;padding:15px 9px}.admin-brand>div,.admin-shell nav p,.admin-shell nav a:not(.active),.admin-shell nav a{font-size:0}.admin-shell nav a{justify-content:center;padding:0}.admin-shell nav a .el-icon{font-size:18px}.return{font-size:0}.return .el-icon{font-size:17px}.admin-shell main{padding:22px 18px}}
</style>
<style scoped>.admin-shell > section > header { position: static; }</style>
