<template><div class="org-page"><header><div><h1>企业工作区</h1><p>工作区状态、成员和项目使用情况</p></div><el-input v-model="search" :prefix-icon="Search" clearable placeholder="搜索企业名称、标识或邮箱" @keyup.enter="load(1)"/><el-button type="primary" @click="load(1)">搜索</el-button></header><section class="org-table surface"><div class="table-title"><strong>全部企业</strong><span>{{page?.total||0}} 个工作区</span></div><el-table :data="page?.items||[]"><el-table-column label="企业" min-width="230"><template #default="scope"><div class="org-name"><span>{{scope.row.name.slice(0,1)}}</span><div><strong>{{scope.row.name}}</strong><small>{{scope.row.slug}}</small></div></div></template></el-table-column><el-table-column label="状态" width="120"><template #default="scope"><el-tag :type="scope.row.status==='active'?'success':'warning'">{{scope.row.status==='active'?'正常使用':'已暂停'}}</el-tag></template></el-table-column><el-table-column prop="members_count" label="成员" width="100"/><el-table-column prop="projects_count" label="项目" width="100"/><el-table-column prop="usage" label="使用量" width="110"/><el-table-column label="创建日期" width="130"><template #default="scope">{{new Date(scope.row.created_at).toLocaleDateString('zh-CN')}}</template></el-table-column><el-table-column label="操作" width="130" align="right"><template #default="scope"><el-button v-if="scope.row.status==='active'" link type="danger" @click="suspend(scope.row)">暂停</el-button><el-button v-else link type="success" @click="activate(scope.row)">恢复</el-button></template></el-table-column></el-table><el-pagination layout="prev, pager, next" :total="page?.total||0" :page-size="20" @current-change="(p:number)=>load(p)"/></section></div></template>
<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { Search } from '@element-plus/icons-vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { adminApi } from '../api/admin'
import type { AdminOrganization, AdminPage } from '../types'
const search = ref('')
const page = ref<AdminPage<AdminOrganization> | null>(null)
const load = async (pageNumber = 1) => { page.value = await adminApi.organizations(pageNumber, search.value) }
const suspend = async (row: AdminOrganization) => { try { const { value } = await ElMessageBox.prompt('请输入暂停原因', '暂停企业工作区', { inputPattern: /.+/, inputErrorMessage: '请填写原因', confirmButtonText: '确认暂停', cancelButtonText: '取消' }); await adminApi.suspendOrganization(row.id, value); ElMessage.success('工作区已暂停'); await load() } catch { /* cancelled */ } }
const activate = async (row: AdminOrganization) => { await adminApi.activateOrganization(row.id); ElMessage.success('工作区已恢复'); await load() }
onMounted(load)
</script>
<style scoped>.org-page header p, .org-name small { display: none; }</style>
<style scoped>.org-page{max-width:1320px;margin:0 auto}.org-page>header{display:flex;align-items:flex-end;gap:10px;margin-bottom:24px}.org-page>header>div{margin-right:auto}.org-page h1{margin:0;font-size:30px;letter-spacing:-.04em}.org-page header p{margin:7px 0 0;color:#86868b;font-size:11px}.org-page header .el-input{width:280px}.org-table{padding:12px 16px 18px;overflow:hidden}.table-title{display:flex;align-items:center;gap:9px;padding:10px 6px 18px}.table-title strong{font-size:14px}.table-title span{color:#86868b;font-size:9px}.org-name{display:flex;align-items:center;gap:10px}.org-name>span{width:34px;height:34px;display:grid;place-items:center;border-radius:11px;color:#515154;background:#ededf0;font-weight:700}.org-name strong,.org-name small{display:block}.org-name strong{font-size:11px}.org-name small{margin-top:3px;color:#86868b;font-size:8px}.el-pagination{justify-content:flex-end;margin-top:17px}@media(max-width:700px){.org-page>header{align-items:flex-start;flex-direction:column}.org-page header .el-input{width:100%}}</style>
